animations {
    enabled = yes

    bezier = snappy, 0.1, 1, 0.1, 1

    animation = windows, 1, 2, snappy, popin
    animation = windowsOut, 1, 2, snappy, popin
    animation = fade, 1, 2, snappy
    animation = workspaces, 1, 3, snappy, slide
    animation = layers, 1, 2, snappy, fade
}
