general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Nuanced Silver/Gray Gradient
    col.active_border = rgba(e0e0e0ee) rgba(a0a0a0ee) 45deg
    col.inactive_border = rgba(333333aa)

    layout = dwindle
}
