font_family IosevkaTerm Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no
font_size 11.0
# text_composition_strategy legacy
modify_font cell_width 95%

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.15
cursor_shape block
cursor_blink true

# Themes can override any settings in this file
include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
confirm_os_window_close 0

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no

allow_remote_control yes
# enabled_layouts tall

editor nvim

colorterm truecolor

# Inicia uma sessão tmux customizada na inicialização
# startup_session ~/.config/kitty/tmux.session
